"""Type stubs for adapter protocols."""

from typing import Any, NewType, Protocol, runtime_checkable

SanitizedStreamName = NewType("SanitizedStreamName", str)

@runtime_checkable
class JetStreamMessage(Protocol):
    metadata: Any
    data: bytes
    headers: Any | None
    async def ack(self) -> None: ...
    async def nak(self, delay: float | None = ...) -> None: ...
    async def in_progress(self) -> None: ...

@runtime_checkable
class MessageHeaders(Protocol):
    def get(self, key: str, default: Any = ...) -> Any: ...
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def keys(self) -> Any: ...
